stages:
  - build
  - test
  - sonarqube
 
build:
  stage: build
  script:
    - cd ./carservice-sprinboot-backend
    -  mvn $MAVEN_CLI_OPTS compile
 
test:
  stage: test
  dependencies:
    - build
  script:
    - cd ./carservice-sprinboot-backend
    - mvn $MAVEN_CLI_OPTS test
 
sonarqube:
 stage: sonarqube
 dependencies:
   - test
 script:
   - cd ./carservice-sprinboot-backend
   - mvn verify sonar:sonar -Dsonar.qualitygate.wait=true

after_script:
  - echo "End CI"